# -*- coding: utf-8 -*-
"""팀_프로젝트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPkniZMdxFrcWaAymadjvOLpafgU8q-z
"""

#팀 프로젝트 아키네이터
import csv
import time
class Akinator:
  def __init__(self):
    self.guess_list=[]
  def open_file(self,f):
    self.file=open(f,'r')
  def sort_file(self):
    self.dic_list=[]
    dic=csv.DictReader(self.file)
    for i in dic:
      self.dic_list.append(i)
  def ask_gender(self):
    gender=None
    while gender not in ['남','여']:
      gender=input('생각하시는 분이 남자이십니까 여자이십니까? 남, 여로 입력해주십시오.')
    for i in self.dic_list:
      if i['성별']==gender:
        self.guess_list.append(i['이름'])
  def ask_sbject(self):
    sb=None
    while sb not in ['수학','과학','컴퓨팅']:
      sb=input('교수님의 주과목이 무엇이십니까? 수학,과학,컴퓨팅 중에 선택해주세요.')
    for i in self.dic_list:
      if i['과목']!=sb:
        if i['이름'] in self.guess_list:
          self.guess_list.remove(i['이름'])
  def ask_glasses(self):
    glasses=None
    while glasses not in ['네','아니요']:
      glasses=input('그 교수님은 안경을 자주 쓰시나요? 네,아니요로 답해주세요.')
    for i in self.dic_list:
      if i['안경']!=glasses:
        if i['이름'] in self.guess_list:
          self.guess_list.remove(i['이름'])
  def play(self):
    self.open_file('교수진.csv')
    self.sort_file()
    print('안녕하세요. 전 과시시 아키네이터입니다. 제가 묻는 질문에 답을 해주신다면 생각하시는 교수님을 맞춰드리겠습니다.')
    print('첫번째 질문입니다.')
    self.ask_gender()
    print('두번째 질문입니다.')
    self.ask_sbject()
    print('세번째 질문입니다.')
    self.ask_glasses()
    print('결과에 대해 분석중입니다...')
    time.sleep(5)
    if len(self.guess_list)==1:
      name=''.join(self.guess_list)
      result=None
      while result not in ['네', '아니요']:
        result=input('생각하시는 교수님이 {} 교수님이 맞으신가요? 네 아니요로 답해주세요.'.format(name커))
        if result=='네':
          print('제가 맞췄군요 !!')
          print('이대로 게임을 종료하겠습니다.')
        if result=='아니요':
          print('정말 틀렸나요..?')
          print('다시 한번 도전해주시죠.')
    if len(self.guess_list)<1:
      print('정확하게 답하신게 맞으십니까? 정답을 찾지 못했습니다.')
    if len(self.guess_list)>1:
      print('한명으로 좁히지는 못하였지만 이중에 생각하시는 분이 존재합니까?')
      print(','.join(self.guess_list))
